Fix Issue 2393
google/error-prone pull request #2470
Opened 2021-07-27 01:35 UTC by openamiguel

Fix for Issue #2393 (WrongOneof mishandles new style switch statement) based on PR #2371 and PR #2124.

2021-07-28 12:50 UTC, openamiguel commented
@googlebot I signed it!

2021-07-30 02:50 UTC, cushon requested changes
Thanks for the fix! Can you also add a test?

2021-07-30 11:46 UTC, openamiguel commented
Sure. There isn't any WrongOneofTest currently. Can I just focus on testing that this bug pattern works on new-style switch statements?

2021-07-30 16:11 UTC, cushon commented
> There isn't any WrongOneofTest currently. Can I just focus on testing that this bug pattern works on new-style switch statements?

Sorry, we have an internal test for this, but it isn't available in open source to avoid the proto dependency in the maven build. Since there isn't already an existing test, this is fine.

2021-07-30 16:11 UTC, cushon approved these changes

2021-08-06 15:32 UTC, openamiguel commented
@cushon thanks for the approval! Are we waiting for additional review?

2021-08-06 15:45 UTC, cushon commented
> Are we waiting for additional review?

Yes, there's a separate internal review step before the PR is merged

2021-08-12 21:13 UTC, closed without merging