Ignore disabled checks passed to `-XepPatchChecks`
google/error-prone pull request #4028
Opened 2023-07-31 10:48 UTC by oxkitsune

Rather than throwing an `NoSuchElementException`.

Fixes #3908.

2023-07-31 11:03 UTC, rickie approved these changes

2023-07-31 11:42 UTC, Stephan202 approved these changes
@oxkitsune these PRs are generally merged with the PR text as commit message, so I would also add this sentence to the PR body (just like in the commit message):
> Rather than throwing an `NoSuchElementException`.

2023-07-31 12:03 UTC, rickie commented
> @oxkitsune these PRs are generally merged with the PR text as commit message, so I would also add this sentence to the PR body (just like in the commit message):

That's already the case right? It should be good like it is right now.

2023-07-31 12:05 UTC, Stephan202 commented
I would swear that my browser didn't show it. But I must have been confused. :thinking:

2023-07-31 17:52 UTC, cushon approved these changes

2023-08-09 14:41 UTC, cushon approved these changes

2023-09-07 18:10 UTC, cushon approved these changes

2023-09-07 21:35 UTC, cushon commented
Thanks for this fix!

I finally did some internal testing of this, and one thing I encountered is that this changes of behaviour of things like `-Xep:DeadException:WARN -XepPatchChecks:GetClassOnClass`--previously refactorings weren't emitted for `DeadException` even though it was explicitly enabled, because it wasn't listed in `-XepPatchChecks`. With this change refactorings are emitted for `DeadException`.

Do you have thoughts on what the least surprising behaviour here would be?

2023-09-08 16:11 UTC, cushon requested changes
Un-approving until the question in https://github.com/google/error-prone/pull/4028#issuecomment-1710798061 is resolved

2023-09-08 16:15 UTC, oxkitsune commented
> Do you have thoughts on what the least surprising behaviour here would be?

Personally I think it would make the most sense, if checks passed to `-Xep:PatchChecks` are the only checks emitting patches, unless they're explicitly disabled.

2023-09-08 18:11 UTC, cushon commented
> > Do you have thoughts on what the least surprising behaviour here would be?
> 
> Personally I think it would make the most sense, if checks passed to `-Xep:PatchChecks` are the only checks emitting patches, unless they're explicitly disabled.
> 
> E.g.
> 
> ```
> -Xep:DeadException:WARN -XepPatchChecks:GetClassOnClass
> ```
> 
> would emit patches for `GetClassOnClass`, and warnings for `DeadException`.
> 
> ```
> -Xep:DeadException:OFF -XepPatchChecks:GetClassOnClass,DeadException
> ```
> 
> would emit _just_ patches for `GetClassOnClass`

That sounds good to me.

I think that there isn't an order that `applyOverrides` and `filter` can be called in that does quite what we want here: calling `applyOverrides` first causes #3908, and calling `filter` first causes refactorings to be emitted for checks that are explicitly enabled with `-Xep:` flags.

I wonder if it makes sense of `-XepPatchChecks` to just override any `-Xep:...:[OFF|WARN|ERROR]` flags. That would mean that we went back to the pre-`2.19` behaviour where refactorings were emitted for `-Xep:CheckName:OFF -XepPatchChecks:CheckName`. Would that work for you?

2023-09-08 18:11 UTC, cushon commented on core/src/test/java/com/google/errorprone/scanner/ScannerTest.java
> +
Can you add another test case for

```java
  @Test
  public void dontRunPatchUnlessRequested() {
    compilationHelper
        .addSourceLines(
            "Test.java",
            "import com.google.errorprone.scanner.ScannerTest.Foo;",
            "class Test {",
            "  Foo foo;",
            "}")
        .setArgs(
            "-XepPatchLocation:IN_PLACE",
            "-Xep:ShouldNotUseFoo:WARN",
            "-XepPatchChecks:DeadException")
        .doTest();
  }
  ```

2023-09-11 05:28 UTC, Stephan202 commented
> I wonder if it makes sense of `-XepPatchChecks` to just override any `-Xep:...:[OFF|WARN|ERROR]` flags. That would mean that we went back to the pre-`2.19` behaviour where refactorings were emitted for `-Xep:CheckName:OFF -XepPatchChecks:CheckName`. Would that work for you?

I'll need to find some time later to think this through more thoroughly, but I wonder whether we'll regret that if #947 is ever merged (still hoping :wink:): then `-XepPatchChecks:` (without further args) would enable patching for all checks, and realistically users will want to apply some exclusions.

That said, we have the #947 change [in our fork](https://github.com/PicnicSupermarket/error-prone/compare/v2.21.1...v2.21.1-picnic-1), and right now we do have this "patch all except those that are `OFF`" behavior, with a baseline more recent than 2.19.

Easiest is perhaps to first add a few more tests, and then assess impact on #947.

2023-09-11 18:13 UTC, cushon commented
> I'll need to find some time later to think this through more thoroughly

My too, I think :)

The existing logic only calls filter if `!namedCheckers.isEmpty()`, if we keep that part and do the rest of what I described, I think that would interact well with #947

i.e. something like:

```java
                  ScannerSupplier toUse = ErrorPronePlugins.loadPlugins(scannerSupplier, context);
                  ImmutableSet<String> namedCheckers = epOptions.patchingOptions().namedCheckers();
                  if (!namedCheckers.isEmpty()) {
                    toUse = toUse.filter(bci -> namedCheckers.contains(bci.canonicalName()));
                  } else {
                    toUse = toUse.applyOverrides(epOptions);
                  }
                  return ErrorProneScannerTransformer.create(toUse.get());
```

2023-09-13 17:27 UTC, Stephan202 commented
Rebased this branch to include the changes of #947 (diff applied cleanly; thanks for merging @cushon!), which should make it marginally easier to reason about the solution space. (Actual reasoning still TBD :sweat_smile:)

2024-03-01 09:43 UTC, oxkitsune commented
Hey @cushon apologies for the inactivity :sweat_smile: 
I've just applied the suggestions and I'm happy with this solution!

2024-03-04 16:46 UTC, cushon commented
> Hey @cushon apologies for the inactivity 😅 I've just applied the suggestions and I'm happy with this solution!

No worries, thanks for coming back to this!

2024-03-04 16:46 UTC, cushon approved these changes

2024-03-05 21:49 UTC, closed without merging